deployment:
  tasks:
    - export NODE_OPTIONS="--openssl-legacy-provider"
    - /usr/local/bin/npm install --omit=dev
    - /usr/local/bin/npm run build
    - /usr/local/bin/pm2 reload erp-web || \
      /usr/local/bin/pm2 serve build 3000 -f --spa --name erp-web
