---                # top of file unchanged
deployment:
  tasks:
    - /bin/bash -lc 'npm ci --omit=dev --no-progress'
    - /bin/bash -lc 'mkdir -p tmp && touch tmp/restart.txt'
      #                                ▲  remove the ampersand
