# .cpanel.yml
deployment:
  tasks:
    # 1. прод package-уудыг суулгах
    - /usr/bin/npm ci  --omit=dev
    # 2. Node Selector-ын app-аа restart хийх
    - /opt/cloudlinux/selectorctl  --interpreter=node  --user=$CPANEL::USER  restart $DEPLOYMENT_DIR
